companieshouse/applications.developer.web.ch.gov.uk

server/routes/applications.js
server/views/_partials/nav_bar.njk
server/views/applications/add.njk

fix logic in nav-bar so that the correct page is highlighted when on it

feature: create add application page

---

app/public/css/app.css
server/routes/applications.js
server/views/_partials/banner.njk

Changed routing to return view all applications on page on manage-applications route.
Altered CSS to fix header fonts and width issues that were causing spacing errors.

feature: header spacing and base routing changes

---

routes.yaml

Hopefully resolving route conflicts.

updated routes.yaml to hopefully work

---

package.json

Temporarily lowers coverage thresholds to help fix build issues

test: temporarily lower coverage thresholds to sort out build gremlins

---

server/views/_partials/nav_bar.njk

Add correct link to view applications

feature: add correct link to view applications

---

server/views/applications/add.njk
server/views/applications/view.njk

Add correct links to `view applications` in route partials

feature: add correct link to view applications in route partials

---

Makefile
package-lock.json
package.json
server/routes/applications.js
server/services/ApplicationsDeveloper.js
server/services/index.js
server/views/_layouts/default.njk
server/views/_partials/__styles.njk
server/views/_partials/error_summary.njk
server/views/_partials/nav_bar.njk
server/views/applications/index.njk

- integrate app overview pages with api
- application displays data from database
- add sonar to the Makefile dist task. as it was defined but unused

Show application overview with real data

---

server/routes/applications.js
server/views/_layouts/default.njk
server/views/_partials/__footer.njk
server/views/_partials/__header.njk
server/views/applications/index.njk

Rectified issues thrown by html validator and added list of future applications to test-list-display

fix: rectify issues as thrown by html validator

---

server/routes/applications.js
server/views/applications/add_key.njk

__Short description outlining key changes/additions__
Added a page for adding a new key now exists.
__JIRA Ticket Number__
FA-598
 
 
 
 
* [ n/a ] I have added unit tests for new code that I have added
* [ n/a ] I have added/updated functional tests where appropriate
 
__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

feature: Page for adding a new key now exists

---

server/routes/applications.js
server/views/_partials/banner.njk
server/views/applications/add_key.njk
server/views/applications/edit.njk

- Removed the unneeded title from the svg.
- removed duplicate ids.
- altered the radio button group in add_key.njk so that the keyboard can land on them.

Resolve Validation problems for the static pages

---

server/views/_partials/banner.njk

-Added title to the companies house crown logo inn banner.njk

Fixed validation error with svg title

---

server/routes/applications.js
server/views/applications/edit.njk
test/server/routes/applications.test.js

fix: change redirect after updating or cancel

---

server/routes/applications.js
server/views/applications/delete_key.njk

User experience improvement based on testing observations.
Reformatted form to be more descriptive to user.
https://companieshouse.atlassian.net/browse/FA-800

feature: improve formatting of key field for better user experience.

---

server/views/applications/delete_key.njk

Corrected where cancel returns to.

bug: fix incorrect link address.

---

server/routes/applications.js
server/services/ApplicationsDeveloper.js
server/views/applications/add.njk
server/views/applications/edit.njk
test/server/routes/applications.test.js
test/server/services/ApplicationDeveloper.test.js

- Add relevant unit tests
- Match views with prototype
- Change update application route to allow for confirmation when deleting app

feature: add functionality to delete a single application

---

server/routes/utils/authentication.js

redirect application to dev hub home
resolves: fa-822

redirect application to dev hub home

---

app/public/css/app.css
server/routes/applications.js
server/views/applications/view.njk
test/server/routes/applications.test.js

Confirmation message for updated keys with appropriate styling

fix: confirmation of key update

---

server/lib/errors/error_manifest.js
server/lib/validation/form_validators/ManageApplication.js
server/lib/validation/index.js
server/views/applications/add_key.njk
server/views/applications/update_key.njk
test/server/lib/validation/form_validators/ManageApplications.test.js

Added validation for restricted ip addresses and javascript domains on addKey and updateKey

feature: validation for restricted ips and js domains

---

server/routes/applications.js

- For delete a key page
- FA-863

fix: broken key type

---

server/views/applications/update_key.njk

Removed feature that was unsupported.

bug: remove invalid 'regenerate key' button.

---

server/views/applications/view.njk

https://companieshouse.atlassian.net/browse/FA-937

feature: fix displayed fields

---

server/lib/errors/error_manifest.js
server/lib/validation/form_validators/ManageApplication.js
server/views/applications/add_key.njk
test/server/lib/validation/form_validators/ManageApplications.test.js

https://companieshouse.atlassian.net/browse/FA-937
Set up redirect URI validation

feature: implement redirect uri validation.

---

server/services/ApplicationsDeveloper.js
test/server/routes/applications.test.js
test/server/services/ApplicationDeveloper.test.js

feature: update service to include check for incorrect key type

---

server/views/applications/view.njk

feature: enabled client secret to be displayed correctly
Jira ticket: https://companieshouse.atlassian.net/browse/FA-912

feature: enabled client secret to be displayed correctly

---

server/lib/errors/error_manifest.js
server/lib/validation/form_validators/ManageApplication.js
server/views/applications/add.njk
server/views/applications/add_key.njk

Change content and styling of error messages for consistency with prototype.

fix: make styling for error messages consistent with prototype

---

package-lock.json

https://companieshouse.atlassian.net/browse/FA-923

chore: updated yargs parser according to dependabot alert

---

server/views/applications/view.njk

-add gov css class to adjust font-size so client secret is always displayed fully

-add gov css class to adjust font-size

---

server/views/applications/add.njk
server/views/applications/add_key.njk

A few other changes required in order to make styling consistent with prototype.

fix: make styling consistent

---

server/routes/applications.js
server/views/applications/add.njk
server/views/applications/edit.njk
server/views/applications/update_key.njk
server/views/applications/view.njk

- changed links for "back to application/s" to match prototype
- removed commented code

fa-951 confirm view application page matches the prototype

---

server/lib/errors/error_manifest.js

- changed error manifest messages for privacy policy url and terms and conditions url to match the prototype

fa-899/fa-900 fix error manifest messages for the urls

---

app/src/js/__global.js

- cleared the fields that would be hidden by changing key type when adding a key to an application

fa-981 Hidden fields causing validation errors

---

server/lib/errors/error_manifest.js
server/lib/validation/form_validators/ManageApplication.js
server/lib/validation/index.js
test/server/lib/validation/form_validators/ManageApplications.test.js
test/server/lib/validation/index.test.js

- added new method to match applications.api regex
- altered tests to match new method
- fixed domain tests that were skipped
- Altered error manifest message given to users
Jira ticket: https://companieshouse.atlassian.net/browse/FA-1048

fa-1048 fix redirect uri regex

---

server/views/applications/edit.njk
server/views/applications/update_key.njk

- added form group error logic to div tags with the class govuk-form-group to edit.njk and update_key.njk
Jira ticket: https://companieshouse.atlassian.net/browse/FA-1050

fa-1050 fix error styling

---

server/views/applications/index.njk

Add application description when viewing all applications

---

server/lib/errors/error_manifest.js

- added new message as specified in the design confluence page
Jira ticket:  https://companieshouse.atlassian.net/browse/FA-898

fa-898 change server error message

---

server/lib/errors/error_manifest.js
server/lib/validation/form_validators/ManageApplication.js
server/lib/validation/index.js
server/routes/applications.js
test/server/routes/applications.test.js

Fixes  security vulnerabilities in Developer Applications Web Service as reported by SonarQube.

Task/CC-4: Fix security vulnerabilities

---

server/lib/Utility.js
server/lib/validation/index.js
server/routes/applications.js
test/server/lib/Utility.test.js

- Adds validation for GET parameters used in redirects
- Removes unused utility method

Task/CC-4/: Fix security vulnerabilities

---

test/server/routes/applications.test.js

Test: Fix failing unit tests

---

server/routes/applications.js

Use filtered variable in redirect

Fix: Use filtered variable in redirect

---

server/lib/validation/form_validators/ManageApplication.js

Removes cognitive complexity from `appId` and `env` filter

Refactor: Remove cognitive complexity from appId and env filter

---

server/lib/validation/index.js
test/server/lib/validation/index.test.js

Adds unit tests for new validation methods

Test: Add unit tests for new validation methods

---

server/lib/APIClientHelper.js
server/routes/applications.js
test/server/_fakes/data/routes/application.js
test/server/_fakes/data/services/private_ch_sdk_node.js
test/server/lib/validation/form_validators/ManageApplications.test.js
test/server/routes/applications.test.js
test/server/services/ApplicationDeveloper.test.js

Bumps up unit test coverage to fix sonar failures

Task/CC-118: Bump up coverage to fix sonar failures

---

terraform/groups/ecs-service/data.tf
terraform/groups/ecs-service/locals.tf
terraform/groups/ecs-service/main.tf
terraform/groups/ecs-service/profiles/development-eu-west-2/cidev/vars
terraform/groups/ecs-service/variables.tf

This is for [CC-667](https://companieshouse.atlassian.net/browse/CC-667)
New features
- fargate
- autoscaling
- global vars
- Cloud watch alerting
[CC-667]: https://companieshouse.atlassian.net/browse/CC-667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CC-667 Refactoring to include recent features.

---

server.js
server/router.js

chore: minor formatting change

---

README.md

CC-1793 Add endpoints to README

CC-1793 Add endpoints to README

---

README.md

This pr will add space in applications.developer.web.ch.gov.uk so we can add it to sbom dashboard where we can monitor the vulnerabilities ,this resolves https://companieshouse.atlassian.net/browse/CC-2022

Adding sbom for the repo
